deathvalleydogs/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

# urlpatterns = patterns('',
#     # Examples:
#      url(r'^$', 'deathvalleydogs.views.home', name='home'),
#     # url(r'^blog/', include('blog.urls')),
#
# )

urlpatterns = patterns(
    'deathvalleydogs.views',

    url(r'^admin/', include(admin.site.urls)),

    (r'^$', 'home.home'),
    (r'^home/$', 'home.home'),
    (r'^writeups/(?P<writeup_id>\d+)/$', 'writeup.detail'),

    (r'^trips/$', 'trip.index'),
    (r'^trips/(?P<trip_id>\d+)/$', 'trip.detail'),

    (r'^hikes/$', 'hike.index'),
    (r'^hikes/(?P<hike_id>\d+)/$', 'hike.detail'),

    (r'^dogs/$', 'dog.index'),
    (r'^dogs/(?P<dog_id>\d+)/$', 'dog.detail'),

    (r'^rigs/$', 'rig.index'),
    (r'^rigs/(?P<rig_id>\d+)/$', 'rig.detail'),

)

deathvalleydogs/models.py
from django.db import models
from datetime import datetime


class ModelBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True, default=datetime.now)

    class Meta:
        abstract = True


class Dog(ModelBase):
    name = models.CharField(max_length=200)
    ham = models.CharField(max_length=200)
    active = models.BooleanField(default=True)
    birth_date = models.DateField('birth date', null=True)
    family = models.CharField(max_length=20)
    known_for = models.CharField(max_length=300, blank=True)

    def __unicode__(self):
        return self.name


class Rig(ModelBase):
    dog = models.ForeignKey(Dog)
    name = models.CharField(max_length=200)
    year = models.IntegerField()
    make = models.CharField(max_length=30)
    model = models.CharField(max_length=30)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class Trip(ModelBase):
    dogs = models.ManyToManyField(Dog, related_name="trips")
    rigs = models.ManyToManyField(Rig, related_name="trips")
    name = models.CharField(max_length=200)
    date = models.DateField()
    end_date = models.DateField(null=True)
    map_points = models.TextField(null=True, default="<kml></kml>")

    def __unicode__(self):
        return self.name


class Hike(ModelBase):
    trip = models.ForeignKey(Trip)
    dogs = models.ManyToManyField(Dog, related_name="hikes")
    name = models.CharField(max_length=200)
    date = models.DateField()
    map_points = models.TextField(null=True, default="<kml></kml>")

    def __unicode__(self):
        return self.name


class Writeup(ModelBase):
    dog = models.ForeignKey(Dog)
    trip = models.ForeignKey(Trip)
    hike = models.ForeignKey(Hike, blank=True, null=True)
    name = models.CharField(max_length=200)
    short_desc = models.CharField(max_length=200)
    body = models.TextField()

    def __unicode__(self):
        return self.name


class Quote(ModelBase):
    quote = models.TextField()
    credit = models.CharField(max_length=40)

    def __unicode__(self):
        return self.quote

deathvalleydogs/views/dog.py
from django.shortcuts import render_to_response, get_object_or_404
from deathvalleydogs.models import Dog
from django.template import RequestContext
from datetime import date

def index(request):
    dog_list = Dog.objects.filter(active=True).order_by('name')
    return render_to_response('dog_index.html', {'dog_list': dog_list},
                              context_instance=RequestContext(request))

def detail(request, dog_id):
    d = get_object_or_404(Dog, pk=dog_id)
    return render_to_response('dog_detail.html', {'dog': d, 'age': age(d.birth_date)},
                              context_instance=RequestContext(request))

def age(from_date, leap_day_anniversary_Feb28=True):
    return date.today().year - from_date.year

deathvalleydogs/views/hike.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from deathvalleydogs.models import Hike, Writeup
# Create your views here.

def index(request):
    hike_list = Hike.objects.all().order_by('date')
    return render_to_response('hike_index.html', {'hike_list': hike_list},
                              context_instance=RequestContext(request))

def detail(request, hike_id):
    t = get_object_or_404(Hike, pk=hike_id)
    return render_to_response('hike_detail.html', {'hike': t},
                              context_instance=RequestContext(request))

deathvalleydogs/views/home.py
from deathvalleydogs.models import Trip, Writeup
from django.template import RequestContext
from django.shortcuts import render_to_response

def home(request):
    latest_writeups = Writeup.objects.all().order_by('created_at')[:5]
    #latest_photos =
    return render_to_response('home.html', {'latest_writeups': latest_writeups},
                              context_instance=RequestContext(request))

deathvalleydogs/views/rig.py
from django.shortcuts import render_to_response, get_object_or_404
from deathvalleydogs.models import Rig
from django.template import RequestContext
from datetime import date

def index(request):
    rig_list = Rig.objects.filter(active=True).order_by('name')
    return render_to_response('rig_index.html', {'rig_list': rig_list},
                              context_instance=RequestContext(request))

def detail(request, rig_id):
    r = get_object_or_404(Rig, pk=rig_id)
    return render_to_response('rig_detail.html', {'rig': r},
                              context_instance=RequestContext(request))

deathvalleydogs/views/trip.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from deathvalleydogs.models import Trip
# Create your views here.

def index(request):
    trip_list = Trip.objects.all().order_by('date')
    return render_to_response('trip_index.html', {'trip_list': trip_list},
                              context_instance=RequestContext(request))

def detail(request, trip_id):
    t = get_object_or_404(Trip, pk=trip_id)
    return render_to_response('trip_detail.html', {'trip': t},
                              context_instance=RequestContext(request))

deathvalleydogs/views/writeup.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from deathvalleydogs.models import Writeup
# Create your views here.

def detail(request, writeup_id):
    t = get_object_or_404(Writeup, pk=writeup_id)
    return render_to_response('writeup_detail.html', {'writeup': t},
                              context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html>
<head>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/dvdogs.css" media="screen, projection"/>
	<title>{% block title %}Death Valley Dogs{% endblock %}</title>
</head>
<body>

<div id="mainImageHeader">
  <div id="header">
    <ul>
      <li id="home" class="tab"><a href="/home">Home</a></li>
      <li id="trips" class="tab"><a href="/trips">Trips</a></li>
      <li id="dogs" class="tab"><a href="/dogs">Dogs</a></li>
      <li id="photos" class="link_away"><a href="http://photos.deathvalleydogs.com"target="_blank">Photos</a></li>
      <li id="forum" class="link_away"><a href="http://forum.deathvalleydogs.com"target="_blank">Forum</a></li>
    </ul>
  </div>
</div>
<div id="content">
  {% block content %}{% endblock %}
</div>


<script>
	function makeSelected() {
		var idName = "#{{ selected_top_tab }}";

		if ($(idName).hasClass("tab")) {
			$(idName).removeClass("tab");
			$(idName).addClass("selected_tab");
		}

	}

	$(document).ready(makeSelected());

</script>
</body>

templates/dog_detail.html
{% extends "base.html" %}

{% block title %}{{ dog }}{% endblock %}
{% block content %}
<h1>{{ dog }}</h1>
<div id="dog_detail" class="detail_page">
    <div class="dog_personal_info">
        <ul>
            <li><div class="label">Age: </div><div class="pers_value">{{ age }}</div></li>
            <li><div class="label">Ham: </div><div class="pers_value">{{ dog.ham }}</div></li>
        </ul>
    </div>
    <div class="rig_list">
        <p>Rigs:</p>
            <ul>
            {% for rig in dog.rig_set.all %}
                <li><a href="/rigs/{{ rig.id }}">{{ rig.name }}</a></li>
            {% endfor %}
            </ul>
    </div>
    <div class="trip_list">
        <p>Trips:</p>
            <ul>
            {% for trip in dog.trips.all %}
                <li><a href="/trips/{{ trip.id }}">{{ trip.name }}</a></li>
            {% endfor %}
            </ul>
    </div>
    <div class="hike_list">
        <p>Hikes:</p>
            <ul>
            {% for hike in dog.hikes.all %}
                <li><a href="/hikes/{{ hike.id }}">{{ hike.name }}</a></li>
            {% endfor %}
            </ul>
    </div>


</div>
{% endblock %}

templates/dog_index.html
{% extends "base.html" %}

{% block title %}Death Valley Dogs{% endblock %}
{% block content %}
<div class="dogCubeContainer">
{% for dog in dog_list %}
  <div class="dogCube">
    <div class="dogImages">

      <a href="/dogs/{{ dog.id }}/"><img src=""></img></a>

      <div class="dogPrint">
            {% if dog.family == "Hominid" %}
                <img src="{{ STATIC_URL }}img/dog-boot-print-white.png"></img>
            {% else %}
                <img src="{{ STATIC_URL }}img/dog-paw-print-white.gif"></img>
            {% endif %}
      </div>
    </div>
    <div class="dogName">
      <a href="/dogs/{{ dog.id }}">{{ dog.name }}</a>
    </div>
  </div>
{% endfor %}
</div>
<div style="clear:both;"></div>
{% endblock %}

templates/hike_detail.html
{% extends "base.html" %}

{% block title %}{{ hike }}{% endblock %}
{% block content %}
<h1>{{ hike }}</h1>
<div class="hike_date">{{ hike.date }}</div>
<div id="hike_detail" class="detail_page">
    <div class="dog_list">
        <p>Dogs:</p>
            <ul>
            {% for dog in hike.dogs.all %}
                <li><a href="/dogs/{{ dog.id }}">{{ dog.name }}</a></li>
            {% endfor %}
            </ul>
    </div>
    <div class="map">
        <p>Map:</p>
        <INPUT TYPE="button" value="Open in Google Earth" onClick="location.href=getMapKml('hikes', <%= @hike.id %>)">
        <div id="map_canvas"></div>

        <script language="javascript" type="text/javascript">
          $("#map_canvas").load(initialize_map('hikes', {{ hike.id }}));
        </script>
    </div>

</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Death Valley Dogs{% endblock %}
{% block content %}

    <div id="latest_writeups">
        {% include "writeup_box.html" with writeups=latest_writeups %}
    </div>

    <div id="last_trip">
    </div>

    <div id="next_trip">
    </div>

{% endblock %}

templates/rig_detail.html
{% extends "base.html" %}

{% block title %}{{ rig }}{% endblock %}
{% block content %}
<h1>{{ rig }}</h1>
<div id="rig_detail" class="detail_page">
    <div class="rig_personal_info">
        <ul>
            <li><div class="label">Owner: </div><div class="pers_value"><a href="/dogs/{{ rig.dog.id }}">{{ rig.dog }}</a></div></li>
            <li><div class="label">Year: </div><div class="pers_value">{{ rig.year }}</div></li>
            <li><div class="label">Make: </div><div class="pers_value">{{ rig.make }}</div></li>
            <li><div class="label">Model: </div><div class="pers_value">{{ rig.model }}</div></li>
        </ul>
    </div>
    <div class="trip_list">
        <p>Trips:</p>
            <ul>
            {% for trip in rig.trips.all %}
                <li><a href="/trips/{{ trip.id }}">{{ trip.name }}</a></li>
            {% endfor %}
            </ul>
    </div>
</div>
{% endblock %}

templates/show_table_list.html
<tr>
  <th>{{ label }}:</th>
  <td>
  	<ul>
   	{% for obj in obj_array %}
        <li>{{ obj.name }}</li>
	{% endfor %}
	</ul>
  </td>
</tr>

templates/trip_detail.html
{% extends "base.html" %}

{% block title %}{{ trip }}{% endblock %}
{% block content %}
<h1>{{ trip }}</h1>
<div class="detail_page">
<div class="trip_date">{{ trip.date }}</div>
<div id="trip_detail" >
    <div class="dog_list">
        <p>Dogs:</p>
            <ul>
            {% for dog in trip.dogs.all %}
                <li><a href="/dogs/{{ dog.id }}">{{ dog.name }}</a></li>
            {% endfor %}
            </ul>
    </div>
    <div class="rig_list">
        <p>Rigs:</p>
            <ul>
            {% for rig in trip.rigs.all %}
                <li><a href="/rigs/{{ rig.id }}">{{ rig.name }}</a></li>
            {% endfor %}
            </ul>
    </div>
    <div class="hike_list">
        <p>Hikes:</p>
            <ul>
            {% for hike in trip.hike_set.all %}
                <li><a href="/hikes/{{ hike.id }}">{{ hike.name }}</a></li>
            {% endfor %}
            </ul>
    </div>
    <div class="writeup_list">
        <p>Writeups:</p>
        {% include "writeup_box.html" with writeups=trip.writeup_set.all %}
    </div>
    <div class="weather">
    </div>
    <div class="map">
        <p>Map:</p>
        <INPUT TYPE="button" value="Open in Google Earth" onClick="location.href=getMapKml('trips', <%= @trip.id %>)">
        <div id="map_canvas"></div>

        <script language="javascript" type="text/javascript">
          $("#map_canvas").load(initialize_map('trips', {{ trip.id }}));
        </script>
    </div>

</div>
</div>
{% endblock %}

templates/trip_index.html
{% extends "base.html" %}

{% block title %}Death Valley Dogs{% endblock %}
{% block content %}
<div class="listOfTrips">
{% for trip in trip_list %}
		<div class="listItem">
            <div class="roundedTitleArea">
                <a href="/trips/{{ trip.id }}/">{{trip.date }} - {{ trip.name}}</a>

            </div>
            <div class="roundedTextArea"><div class="roundedTextAreaHeightFixer"></div>
                <div class="indexItemListHeader"><strong>Hikes</strong></div>
                <div class="hikeListForTripList">
                      {% for hike in trip.hike_set.all %}
                        <li><a href="/hikes/{{ hike.id }}">{{ hike.name }}</a></li>
                      {% endfor %}
                    <div class="clear"></div>
                </div>
                <div class="indexItemListHeader"><strong>Writeups</strong></div>
                <div class="writeupListForTripList">
                      {% for writeup in trip.writeup_set.all %}
                        <li><a href="/writeups/{{ writeup.id }}">{{ writeup.name }}</a></li>
                      {% endfor %}
                </div>
            </div>
        </div>
{% endfor %}
</div>
{% endblock %}

templates/writeup_box.html
{% for writeup in writeups %}


<p>
<div class="writeup_list_item" onclick="window.location.href='/writeups/{{ writeup.id }}';">
    <div class = "writeup_list_image">
        {% if writeup.photo %}
          <img></img>
        {% endif %}
    </div>
    <div class = "writeup_list_text_box">
      <div class="roundedTitleArea">
        {{ writeup.name }} - {{ writeup.trip }}<br>
        by {{ writeup.dog.name }}
      </div>
      <div class="roundedTextArea"><div class="roundedTextAreaHeightFixer"></div>
      {% if writeup.short_desc %}
        {{ writeup.short_desc }}
      {% endif %}
		<div class="clear"></div>
      </div>
    </div>
</div>
</p>

{% endfor %}

templates/writeup_detail.html
{% extends "base.html" %}

{% block title %}Death Valley Dogs{% endblock %}
{% block content %}
<div class="showTitleObject">
    <a href="/trips/{{ writeup.trip.id }}">{{ writeup.name }}</a> - according to
        <a href="/dogs/{{writeup.dog.id}}">{{ writeup.dog.name }}</a>
</div>
<div class="writeup_description detail_page">
    {{ writeup.body|safe }}
</div>
{% endblock %}